In [1]:
# Tabel logika AND 2 input

"""
x1  x2  y
1   1   1
1   0   0
0   1   0
0   0   0
"""

'\nx1  x2  y\n1   1   1\n1   0   0\n0   1   0\n0   0   0\n'

In [73]:
import keras
import numpy as np
from keras import backend as K

# model
model = keras.Sequential()
model.add(keras.layers.Dense(units=1, input_shape=[2]))
model.add(keras.layers.Dense(units=5, name='hidden1', activation="softmax"))
model.add(keras.layers.Dense(units=7, name='hidden2', activation="relu"))
model.add(keras.layers.Dense(units=5, name='hidden3', activation="softmax"))
model.add(keras.layers.Dense(units=1, name='output'))

# model compile
model.compile(optimizer='adam', loss='mean_squared_error')

K.set_value(model.optimizer.learning_rate, 0.001)

# set data
xs = np.array([[1,1], [1,0], [0,1], [0,0]], dtype=int)
ys = np.array([1, 0, 0, 0], dtype=int)

In [74]:
# tampilkan arsitektur awal

model.summary()

Model: "sequential_16"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_16 (Dense)            (None, 1)                 3         
                                                                 
 hidden1 (Dense)             (None, 5)                 10        
                                                                 
 hidden2 (Dense)             (None, 7)                 42        
                                                                 
 hidden3 (Dense)             (None, 5)                 40        
                                                                 
 output (Dense)              (None, 1)                 6         
                                                                 
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________


In [75]:
# cek bobot model awal
weights = model.get_weights()
weights

[array([[-1.2349994],
        [ 1.350444 ]], dtype=float32),
 array([0.], dtype=float32),
 array([[ 0.4221623 ,  0.9002633 , -0.2544546 , -0.8182366 ,  0.16666222]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.6011535 ,  0.47336215,  0.24102283,  0.5960105 ,  0.3903063 ,
         -0.31441212,  0.61594194],
        [-0.6296761 ,  0.6404008 , -0.08854109, -0.5733795 , -0.11688298,
         -0.5241608 ,  0.45939833],
        [ 0.24052835, -0.6083968 ,  0.12633818,  0.2741201 , -0.16909653,
         -0.2012291 , -0.13349628],
        [-0.6091376 , -0.18548101,  0.29361063, -0.393002  ,  0.5773569 ,
          0.4231382 , -0.45657563],
        [ 0.706366  , -0.30033708, -0.13302541, -0.2215122 ,  0.374075  ,
         -0.2807813 ,  0.03987432]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.48936975, -0.07090974,  0.03322452,  0.44098717, -0.01857495],
        [-0.2664839 ,  0.65826756, -0.22084391,  0.3011679 , -0.6257027

In [76]:
# training
model.fit(xs, ys, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 1s 910ms/step - loss: 0.1933
Epoch 2/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.1930
Epoch 3/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.1926
Epoch 4/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.1923
Epoch 5/1000
1/1 [==============================] - 0s 17ms/step - loss: 0.1920
Epoch 6/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.1917
Epoch 7/1000
1/1 [==============================] - 0s 11ms/step - loss: 0.1915
Epoch 8/1000
1/1 [==============================] - 0s 20ms/step - loss: 0.1912
Epoch 9/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.1910
Epoch 10/1000
1/1 [==============================] - 0s 10ms/step - loss: 0.1908
Epoch 11/1000
1/1 [==============================] - 0s 9ms/step - loss: 0.1906
Epoch 12/1000
1/1 [==============================] - 0s 14ms/step - loss: 0.1904
Epoch 13/1000
1/1 [===================

In [77]:
# test
data = [1,1]
answer = model.predict([data])
print(answer)

1/1 [==============================] - 0s 183ms/step
[[1.0000001]]


In [78]:
# cek bobot model akhir
weights = model.get_weights()
weights

[array([[-0.97396123],
        [ 2.1249223 ]], dtype=float32),
 array([-0.24294382], dtype=float32),
 array([[ 0.5910126 ,  1.8036667 , -1.1618462 , -1.475816  ,  0.28053325]],
       dtype=float32),
 array([ 0.6409814 , -0.24962603, -0.0147365 , -0.12098951, -0.66575295],
       dtype=float32),
 array([[-0.6011535 ,  1.3929334 ,  1.085881  ,  0.6860642 ,  1.2197437 ,
         -0.40835145,  1.6002531 ],
        [-0.6296761 ,  0.13899694, -0.2888868 , -0.59620553, -0.15125674,
         -0.6903272 ,  0.05710159],
        [ 0.24052835, -0.7542026 , -0.5532634 ,  0.40753302, -0.8218083 ,
         -0.00391176, -0.30873227],
        [-0.6091376 , -0.45727563, -0.3354883 , -0.4535468 , -0.04155084,
          0.6437285 , -0.74225044],
        [ 0.706366  ,  0.3777235 ,  0.57889843, -0.05548007,  1.0609432 ,
         -0.38522485,  0.8309482 ]], dtype=float32),
 array([ 0.        , -0.18767942,  0.00041899,  0.01929318, -0.14525439,
         0.07612178, -0.37344253], dtype=float32),
 array([[-0.