In [1]:
# table data

"""
w1  = 2
w2  = 4

x1    x2    y
2     3     16
4     1     12
5     4     28
7     5     34
8     2     24
2     1     8
4     9     44
8     2     24
7     1     18
6     5     32
1     1     6
3     2     14

"""

'\nw1  = 2\nw2  = 4\n\nx1    x2    y\n2     3     16\n4     1     12\n5     4     28\n7     5     34\n8     2     24\n2     1     8\n4     9     44\n8     2     24\n7     1     18\n6     5     32\n1     1     6\n3     2     14\n\n'

In [223]:
import numpy as np
import keras
from keras import backend as K

# model
model2 = keras.Sequential()
model2.add(keras.layers.Dense(units=1, input_shape=[2]))
model2.add(keras.layers.Dense(units=7, activation="sigmoid", name="Hidden1"))
model2.add(keras.layers.Dense(units=7, activation="elu", name="Hidden2"))
# model2.add(keras.layers.Dense(units=5, activation="relu", name="Hidden3"))
model2.add(keras.layers.Dense(units=1, name="output"))

# model compile
model2.compile(optimizer='sgd', loss='mean_squared_error')

K.set_value(model2.optimizer.learning_rate, 0.001)

# set data
xs = np.array([[2, 3], [4, 1], [5, 4], [7, 5], [8, 2], [2,1], [4,9], [8,2], [7,1], [6,5], [1,1], [3, 2]], dtype=int)
ys = np.array([16, 12, 28, 34, 24, 8, 44, 24, 18, 32, 6, 14], dtype=int)

model2.summary()

Model: "sequential_54"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_54 (Dense)            (None, 1)                 3         
                                                                 
 Hidden1 (Dense)             (None, 7)                 14        
                                                                 
 Hidden2 (Dense)             (None, 7)                 56        
                                                                 
 output (Dense)              (None, 1)                 8         
                                                                 
Total params: 81
Trainable params: 81
Non-trainable params: 0
_________________________________________________________________


In [224]:
# cek bobot model awal
weights = model2.get_weights()
weights

[array([[ 0.20411754],
        [-0.7092212 ]], dtype=float32),
 array([0.], dtype=float32),
 array([[ 0.11312521, -0.40514332, -0.49544254,  0.6849925 ,  0.36650056,
          0.33365923, -0.25671434]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.09748155,  0.23475266,  0.08165908, -0.29584032, -0.29957086,
          0.11621821, -0.06097752],
        [-0.42943916, -0.17138338,  0.00823504, -0.221484  ,  0.6304133 ,
          0.49520612,  0.40462995],
        [-0.6518639 ,  0.5774727 , -0.60780483, -0.43030354,  0.1852709 ,
         -0.07611287,  0.14676309],
        [ 0.33666897, -0.34726423, -0.05260807,  0.4003266 , -0.55028486,
         -0.41284162,  0.3536495 ],
        [ 0.2770918 , -0.19033027,  0.28898776, -0.00787556, -0.37150058,
          0.42681897, -0.08457673],
        [ 0.08658266,  0.47319853,  0.58427525, -0.15676492,  0.2945953 ,
          0.01987857, -0.5474189 ],
        [ 0.08613646, -0.56757915,  0.43419826,  0.07925403, -0.1956

In [225]:
# training

model2.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 [==============================] - 1s 697ms/step - loss: 600.2527
Epoch 2/500
1/1 [==============================] - 0s 11ms/step - loss: 582.9312
Epoch 3/500
1/1 [==============================] - 0s 7ms/step - loss: 567.0085
Epoch 4/500
1/1 [==============================] - 0s 10ms/step - loss: 552.3530
Epoch 5/500
1/1 [==============================] - 0s 7ms/step - loss: 538.6085
Epoch 6/500
1/1 [==============================] - 0s 5ms/step - loss: 525.4091
Epoch 7/500
1/1 [==============================] - 0s 13ms/step - loss: 512.5598
Epoch 8/500
1/1 [==============================] - 0s 8ms/step - loss: 499.8487
Epoch 9/500
1/1 [==============================] - 0s 6ms/step - loss: 487.0993
Epoch 10/500
1/1 [==============================] - 0s 8ms/step - loss: 474.1835
Epoch 11/500
1/1 [==============================] - 0s 5ms/step - loss: 461.0254
Epoch 12/500
1/1 [==============================] - 0s 8ms/step - loss: 447.5625
Epoch 13/500
1/1 [==============

In [227]:
# test
data = [3,2]
answer = model2.predict([data])
print(answer)



1/1 [==============================] - 0s 104ms/step
[[15.246067]]
