In [1]:
# table data

"""
w1  = 2
w2  = 4

x1    x2    y
2     3     16
4     1     12
5     4     28
7     5     34
8     2     24
2     1     8
4     9     44
8     2     24
7     1     18
6     5     32
1     1     6
3     2     14

"""

'\nw1  = 2\nw2  = 4\n\nx1    x2    y\n2     3     16\n4     1     12\n5     4     28\n7     5     34\n8     2     24\n2     1     8\n4     9     44\n8     2     24\n7     1     18\n6     5     32\n1     1     6\n3     2     14\n\n'

In [417]:
import numpy as np
import keras
from keras import backend as K

# model
model2 = keras.Sequential()
model2.add(keras.layers.Dense(units=1, input_shape=[2]))
model2.add(keras.layers.Dense(units=7, activation="elu", name="Hidden1"))
model2.add(keras.layers.Dense(units=7, activation="relu", name="Hidden2"))
model2.add(keras.layers.Dense(units=3, activation="softmax", name="Hidden3"))
model2.add(keras.layers.Dense(units=1, name="output"))

# model compile
model2.compile(optimizer='sgd', loss='mean_squared_error')

K.set_value(model2.optimizer.learning_rate, 0.001)

# set data
xs = np.array([[2, 3], [4, 1], [5, 4], [7, 5], [8, 2], [2,1], [4,9], [8,2], [7,1], [6,5], [1,1], [3, 2]], dtype=int)
ys = np.array([16, 12, 28, 34, 24, 8, 44, 24, 18, 32, 6, 14], dtype=int)

model2.summary()

Model: "sequential_104"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_104 (Dense)           (None, 1)                 3         
                                                                 
 Hidden1 (Dense)             (None, 7)                 14        
                                                                 
 Hidden2 (Dense)             (None, 7)                 56        
                                                                 
 Hidden3 (Dense)             (None, 3)                 24        
                                                                 
 output (Dense)              (None, 1)                 4         
                                                                 
Total params: 101
Trainable params: 101
Non-trainable params: 0
_________________________________________________________________


In [418]:
# cek bobot model awal
weights = model2.get_weights()
weights

[array([[-1.2090639 ],
        [-0.06993377]], dtype=float32),
 array([0.], dtype=float32),
 array([[-0.41295165,  0.32766873,  0.18291742, -0.5701767 ,  0.46546048,
          0.23225719, -0.49556786]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[ 0.12782317,  0.5744293 , -0.27447465,  0.01267475,  0.3561715 ,
         -0.5147623 , -0.14798564],
        [-0.3740898 , -0.5654418 , -0.43442768, -0.13858956, -0.19234201,
          0.06548619,  0.46875858],
        [-0.5377211 ,  0.56222343, -0.6067697 ,  0.01200861,  0.05702049,
         -0.29333508,  0.2664144 ],
        [-0.6323181 , -0.30026323,  0.51173484,  0.63805115, -0.18177044,
          0.45048678,  0.22479683],
        [-0.6272843 , -0.6167819 ,  0.55872655, -0.27384126,  0.6070225 ,
          0.12340671, -0.5141005 ],
        [-0.1076988 , -0.4102447 , -0.38677675,  0.34629762, -0.30783567,
         -0.5856509 , -0.24417233],
        [-0.27379397,  0.13238043, -0.40517396,  0.19228506,  0.2106

In [419]:
# training

model2.fit(xs, ys, epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 489ms/step - loss: 607.0439
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 602.4539
Epoch 3/500
1/1 [==============================] - 0s 12ms/step - loss: 598.1979
Epoch 4/500
1/1 [==============================] - 0s 7ms/step - loss: 594.1675
Epoch 5/500
1/1 [==============================] - 0s 8ms/step - loss: 590.2766
Epoch 6/500
1/1 [==============================] - 0s 7ms/step - loss: 586.4753
Epoch 7/500
1/1 [==============================] - 0s 9ms/step - loss: 582.7360
Epoch 8/500
1/1 [==============================] - 0s 7ms/step - loss: 579.0439
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 575.3904
Epoch 10/500
1/1 [==============================] - 0s 7ms/step - loss: 571.7706
Epoch 11/500
1/1 [==============================] - 0s 8ms/step - loss: 568.1816
Epoch 12/500
1/1 [==============================] - 0s 5ms/step - loss: 564.6216
Epoch 13/500
1/1 [================

In [420]:
# test
data = [3,2]
answer = model2.predict([data])
print(answer)

1/1 [==============================] - 0s 174ms/step
[[14.043465]]
